'use client';
import {useEffect,useState,useRef} from 'react';
import {Check,Layers,CheckCircle2,Bookmark,Plus,ArrowDownWideNarrow,Clock,CalendarDays,Pencil,X,FileText,Download,RotateCcw} from 'lucide-react';
type Task={id:string;list_id:string;title:string;priority:number;deadline:number|null;done:number};
type List={id:string;title:string;period:string;priority:number;deadline:number|null;done:number};
type Note={id:string;title:string;content:string;filename:string|null;size:number|null};
type Data={user:{displayName:string;email:string};lists:List[];tasks:Task[];notes:Note[];mailReady:boolean};
type Modal={kind:'list'|'task'|'note';item?:any;listId?:string};
const priorities=['Urgent','Must','Not Important'];const periods=['General','Year','Month','Week','Day'];
function due(value:number|null){return value?new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):''}
function localDate(value:number|null){if(!value)return '';const d=new Date(value);return new Date(value-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
export default function Workspace(){
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[auth,setAuth]=useState(false),[error,setError]=useState(''),[page,setPage]=useState('lists'),[period,setPeriod]=useState('All'),[modal,setModal]=useState<Modal|null>(null),[busy,setBusy]=useState(false),[toast,setToast]=useState('');
 const dialog=useRef<HTMLDivElement>(null);const opener=useRef<HTMLElement|null>(null);
 async function refresh(){try{const r=await fetch('/api/workspace');if(r.status===401){setAuth(true);return}const d=await r.json() as Data & {error:string};if(!r.ok)throw Error(d.error);setData(d);setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load your workspace.')}finally{setLoading(false)}}
 useEffect(()=>{refresh();const p=new URLSearchParams(location.search).get('page');if(p==='done'||p==='important')setPage(p)},[]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'start_list_creation',description:'Open the new-list dialog with a name and period. This stages a list; the user must save the form to create it.',inputSchema:{type:'object',properties:{title:{type:'string',maxLength:160},period:{type:'string',enum:periods}},required:['title','period'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const v=input as {title?:unknown;period?:unknown};if(!v||typeof v.title!=='string'||!v.title.trim()||v.title.length>160||typeof v.period!=='string'||!periods.includes(v.period))throw Error('Provide a name and valid period.');setModal({kind:'list',item:{title:v.title,period:v.period}});await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {status:'staged',saved:false}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t)},[toast]);
 useEffect(()=>{if(!modal)return;opener.current=document.activeElement as HTMLElement;const root=dialog.current;root?.querySelector<HTMLElement>('input,button')?.focus();const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy)setModal(null);if(e.key==='Tab'&&root){const els=Array.from(root.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea'));const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);opener.current?.focus()}},[modal,busy]);
 function navigate(next:string){setPage(next);history.replaceState(null,'',next==='lists'?'/':`/?page=${next}`)}
 async function action(payload:any,message:string){setBusy(true);try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await r.json() as {error:string};if(!r.ok)throw Error(result.error);await refresh();setToast(message);return true}catch(e){setError(e instanceof Error?e.message:'Could not save. Please try again.');return false}finally{setBusy(false)}}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!modal)return;const f=new FormData(e.currentTarget);if(modal.kind==='note'){setBusy(true);try{if(modal.item)f.set('id',modal.item.id);const r=await fetch('/api/notes',{method:'POST',body:f});const result=await r.json() as {error:string};if(!r.ok)throw Error(result.error);await refresh();setModal(null);setToast('Saved to Important')}catch(e){setError(e instanceof Error?e.message:'Could not save your item.')}finally{setBusy(false)}return}
 const deadline=f.get('deadline');const ok=await action({action:modal.kind==='list'?'saveList':'saveTask',id:modal.item?.id,listId:modal.listId,title:f.get('title'),priority:Number(f.get('priority')),period:f.get('period'),deadline:deadline?new Date(String(deadline)).getTime():null},'Changes saved');if(ok)setModal(null)}
 const active=data?.lists.filter(l=>!l.done)??[],tasks=data?.tasks??[],openTasks=tasks.filter(t=>!t.done),completed=data?.lists.filter(l=>l.done)??[];
 const effective=(l:List)=>Math.min(l.priority,...tasks.filter(t=>t.list_id===l.id&&!t.done).map(t=>t.priority));
 const lists=(page==='done'?completed:active).filter(l=>period==='All'||l.period===period).sort((a,b)=>effective(a)-effective(b)||(a.deadline??Infinity)-(b.deadline??Infinity)||a.title.localeCompare(b.title));
 const title=page==='important'?'Important things':page==='done'?'Done & kept':'My lists';
 return <><aside><div className="brand"><span className="brand-mark"><Check size={24}/></span>daymark</div><div className="nav-label">YOUR WORKSPACE</div><nav><button className={page==='lists'?'active':''} onClick={()=>navigate('lists')}><Layers size={19}/>My lists</button><button className={page==='done'?'active':''} onClick={()=>navigate('done')}><CheckCircle2 size={19}/>Done</button><button className={page==='important'?'active':''} onClick={()=>navigate('important')}><Bookmark size={19}/>Important</button></nav><div className="sidebar-bottom">{data?.user.email??'Your personal workspace'}{data&&<a href="/signout-with-chatgpt?return_to=/" target="_top">Sign out</a>}</div></aside>
 <main className="app-main"><header className="topbar"><strong>Personal workspace <span style={{color:'#aab4c7',margin:'0 9px'}}>/</span> {page==='important'?'Important':page==='done'?'Done':'My lists'}</strong><div className="account"><span>{data?.user.displayName??'Daymark'}</span><div className="avatar">{data?.user.displayName?.slice(0,1).toUpperCase()??'D'}</div></div></header>
 {auth?<section className="signin"><div className="eyebrow">A little more organized</div><h1>Your plans. One place.</h1><p className="subtle">Keep your lists, deadlines, notes and files together in your private workspace.</p><a className="primary" href="/signin-with-chatgpt?return_to=/" target="_top">Sign in with ChatGPT</a></section>:<><div className="page-heading"><div><h1>{title}</h1><p className="subtle">{page==='important'?'A place for the things you want to keep.':page==='done'?'Finished lists stay here. Reopen them whenever you need.':'Make room for what matters, one task at a time.'}</p></div>{page!=='done'&&<button className="primary" disabled={!data} onClick={()=>setModal({kind:page==='important'?'note':'list'})}><Plus size={18}/>{page==='important'?'Add important':'New list'}</button>}</div>
 {error&&<div role="alert" className="notice error">{error} <button onClick={()=>{setError('');refresh()}}>Retry</button></div>}
 {loading?<div className="loading">Loading your workspace…</div>:data&&<>
 {page!=='important'&&<><div className="stats"><div className="stat"><div className="stat-icon"><Layers size={23}/></div><div><strong>{active.length}</strong><span>Active lists</span></div></div><div className="stat"><div className="stat-icon"><Clock size={23}/></div><div><strong>{openTasks.filter(t=>t.priority===0).length}</strong><span>Urgent tasks</span></div></div><div className="stat"><div className="stat-icon"><CheckCircle2 size={23}/></div><div><strong>{completed.length}</strong><span>Completed lists</span></div></div></div><div className="toolbar"><div className="tabs" aria-label="List period">{['All',...periods].map(p=><button key={p} aria-pressed={period===p} className={period===p?'selected':''} onClick={()=>setPeriod(p)}>{p}</button>)}</div><div className="sort-label"><ArrowDownWideNarrow size={16}/>Priority first</div></div></>}
 {!data.mailReady&&page==='lists'&&<div className="notice">Email reminders are not connected yet. Your deadlines are saved; complete the email setup in the project guide to enable two-hour warnings.</div>}
 <div className="cards">{page==='important'?data.notes.map(n=><article className="card" key={n.id}><div className="card-top"><div className="eyebrow">{n.filename?'FILE + NOTE':'NOTE'}</div><div className="card-title"><h2>{n.title}</h2><button className="icon-button" aria-label={`Edit ${n.title}`} onClick={()=>setModal({kind:'note',item:n})}><Pencil size={16}/></button></div>{n.content&&<p className="note-content">{n.content}</p>}{n.filename&&<a className="file-link" href={`/api/notes?id=${n.id}`}><Download size={17}/>{n.filename} · {Math.ceil((n.size??0)/1024)} KB</a>}</div></article>):lists.map(l=>{const lt=tasks.filter(t=>t.list_id===l.id).sort((a,b)=>a.priority-b.priority||a.done-b.done||(a.deadline??Infinity)-(b.deadline??Infinity)||a.title.localeCompare(b.title)),done=lt.filter(t=>t.done).length;return <article key={l.id} className="card"><div className="card-top"><div className="eyebrow">{l.period} LIST</div><div className="card-title"><h2>{l.title}</h2><span className={`badge priority-${effective(l)}`}>{priorities[effective(l)]}</span></div><div className="progress-line"><div style={{width:`${lt.length?done/lt.length*100:l.done?100:0}%`}}/></div><div className="card-meta"><span>{done} of {lt.length} tasks done</span>{l.deadline&&<span className={`deadline ${!l.done&&l.deadline-Date.now()<7200000?'soon':''}`}>{due(l.deadline)}</span>}</div></div>{lt.map(t=><div key={t.id} className={`task ${t.done?'is-done':''}`}><input className="check" type="checkbox" checked={!!t.done} disabled={busy} aria-label={`Mark ${t.title} ${t.done?'not done':'done'}`} onChange={()=>action({action:'toggleTask',id:t.id,done:!t.done},t.done?'Task reopened':'Task completed')}/><div className="task-body"><div className="task-name">{t.title}</div><div className="task-detail"><span className={`badge priority-${t.priority}`}>{priorities[t.priority]}</span>{t.deadline&&<span className={`deadline ${!t.done&&t.deadline-Date.now()<7200000?'soon':''}`}>{due(t.deadline)}</span>}</div></div><button className="icon-button" aria-label={`Edit ${t.title}`} onClick={()=>setModal({kind:'task',item:t,listId:l.id})}><Pencil size={14}/></button></div>)}<footer className="card-footer">{l.done?<button className="text-button" disabled={busy} onClick={()=>action({action:'setListDone',id:l.id,done:false},'List reopened')}><RotateCcw size={15}/>Reopen list</button>:<button className="text-button" onClick={()=>setModal({kind:'task',listId:l.id})}><Plus size={17}/>Add task</button>}<div style={{display:'flex',gap:12}}>{!l.done&&<button className="text-button" disabled={busy} onClick={()=>action({action:'setListDone',id:l.id,done:true},'List moved to Done')}>Complete list</button>}<button className="icon-button" aria-label={`Edit list ${l.title}`} onClick={()=>setModal({kind:'list',item:l})}><Pencil size={16}/></button></div></footer></article>})}
 {(page==='important'?data.notes.length===0:lists.length===0)&&<div className="empty">{page==='important'?<Bookmark size={37}/>:page==='done'?<CheckCircle2 size={37}/>:<Layers size={37}/>}<h2>{page==='important'?'Keep something worth remembering':page==='done'?'Your wins will live here':'Start with one small list'}</h2><p className="subtle">{page==='important'?'Save a note, a file, or both.':page==='done'?'Complete a list to move it here automatically.':period==='All'?'From a yearly goal to today’s errands.':`Create your first ${period.toLowerCase()} list.`}</p>{page!=='done'&&<button className="primary" onClick={()=>setModal({kind:page==='important'?'note':'list',item:page==='lists'&&period!=='All'?{period}:undefined})}><Plus size={17}/>{page==='important'?'Add important':'Create a list'}</button>}</div>}</div></> }</>}
 </main>{modal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setModal(null)}}><div ref={dialog} className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="modal-header"><h2 id="modal-title">{modal.item?.id?'Edit':modal.kind==='note'?'Save something important':'New'} {modal.kind==='note'?'':modal.kind}</h2><button aria-label="Close dialog" disabled={busy} onClick={()=>setModal(null)}><X size={21}/></button></div>{error&&<div className="notice error" role="alert">{error}</div>}<form onSubmit={submit}><label className="field">{modal.kind==='task'?'Task':modal.kind==='list'?'List name':'Title'}<input name="title" required maxLength={160} defaultValue={modal.item?.title??''} placeholder={modal.kind==='list'?'e.g. A productive week':modal.kind==='task'?'What needs to get done?':'Give it a name'}/></label>{modal.kind==='note'?<><label className="field">Text<textarea name="content" maxLength={20000} defaultValue={modal.item?.content??''} placeholder="Write something you want to keep…"/></label><label className="field">File (optional)<input type="file" name="file"/><small>Up to 10 MB. {modal.item?.filename?`Current: ${modal.item.filename}. A new upload replaces it.`:'Add text, a file, or both.'}</small></label></>:<><div className="form-row">{modal.kind==='list'&&<label className="field">List type<select name="period" defaultValue={modal.item?.period??'General'}>{periods.map(p=><option key={p}>{p}</option>)}</select></label>}<label className="field">Priority<select name="priority" defaultValue={modal.item?.priority??1}>{priorities.map((p,i)=><option key={p} value={i}>{p}</option>)}</select></label></div><label className="field">Deadline (optional)<input type="datetime-local" name="deadline" defaultValue={localDate(modal.item?.deadline??null)}/><small>Shown in your device’s timezone. Leave blank for no deadline.</small></label></>}<div className="modal-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setModal(null)}>Cancel</button><button type="submit" className="primary" disabled={busy}>{busy?'Saving…':modal.item?.id?'Save changes':modal.kind==='note'?'Save important':`Create ${modal.kind}`}</button></div></form></div></div>}{toast&&<div className="toast" role="status">{toast}</div>}</>;
}

