import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '../app/chatgpt-auth';
export class HttpError extends Error{constructor(message:string,public status=400){super(message)}}
export function db(){const binding=(env as unknown as {DB:D1Database}).DB;if(!binding)throw new HttpError('Your storage is temporarily unavailable. Please try again.',503);return binding}
export function bucket(){return (env as unknown as {BUCKET:R2Bucket}).BUCKET}
export async function identity(request?:Request){if(request){const origin=request.headers.get('origin');if(!origin||origin!==new URL(request.url).origin)throw new HttpError('This request must come from your workspace.',403)}const u=await getChatGPTUser();if(!u)throw new HttpError('Please sign in to continue.',401);return u}
export function fail(e:unknown){if(e instanceof HttpError)return Response.json({error:e.message},{status:e.status});console.error('Workspace request failed',e);return Response.json({error:'We could not save or load your data. Please try again.'},{status:503})}
export function title(v:unknown){if(typeof v!=='string'||!v.trim()||v.trim().length>160)throw new HttpError('Use a name between 1 and 160 characters.');return v.trim()}
export function priority(v:unknown){if(v!==0&&v!==1&&v!==2)throw new HttpError('Choose a valid priority.');return v}
export function deadline(v:unknown){if(v===null)return null;if(typeof v!=='number'||!Number.isSafeInteger(v)||v<=0||v>8640000000000000)throw new HttpError('Choose a valid deadline.');return v}
export async function owned(table:'lists'|'tasks'|'notes',id:unknown,owner:string){if(typeof id!=='string')throw new HttpError('Choose an item.');const row=await db().prepare(`SELECT * FROM ${table} WHERE id=? AND owner=? AND deleted_at IS NULL`).bind(id,owner).first<Record<string,any>>();if(!row)throw new HttpError('This item was not found.',404);if(table==='tasks')await owned('lists',row.list_id,owner);return row}
export function mailConfig(){const e=env as unknown as Record<string,string>;return {url:e.REMINDER_BRIDGE_URL,token:e.REMINDER_BRIDGE_TOKEN}}
export function dirty(owner:string){return db().prepare('INSERT INTO mail_state(owner,revision,synced) VALUES(?,1,0) ON CONFLICT(owner) DO UPDATE SET revision=revision+1').bind(owner)}
export async function syncMail(user:{userId:string;email:string}){const cfg=mailConfig();if(!cfg.url||!cfg.token)return false;try{const state=await db().prepare('SELECT revision,synced FROM mail_state WHERE owner=?').bind(user.userId).first<{revision:number;synced:number}>();if(!state||state.revision===state.synced)return true;const items=await db().prepare("SELECT 'list:'||id AS id,title,deadline FROM lists WHERE owner=? AND deleted_at IS NULL AND done=0 AND deadline IS NOT NULL UNION ALL SELECT 'task:'||t.id AS id,t.title,t.deadline FROM tasks t JOIN lists l ON t.list_id=l.id WHERE t.owner=? AND t.deleted_at IS NULL AND l.deleted_at IS NULL AND t.done=0 AND l.done=0 AND t.deadline IS NOT NULL").bind(user.userId,user.userId).all();const url=new URL(cfg.url);if(url.protocol!=='https:')throw Error('Reminder bridge must use HTTPS');const r=await fetch(new URL('/sync',url),{method:'POST',headers:{Authorization:`Bearer ${cfg.token}`,'Content-Type':'application/json'},body:JSON.stringify({owner:user.userId,email:user.email,revision:state.revision,items:items.results}),signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error(`Reminder sync ${r.status}`);await db().prepare('UPDATE mail_state SET synced=MAX(synced,?) WHERE owner=?').bind(state.revision,user.userId).run();return true}catch(e){console.error('Reminder sync failed',e);return false}}
