import {identity,db,fail,title,priority,deadline,owned,HttpError,dirty,syncMail} from '../../../lib/server';
export async function GET(){try{const user=await identity();const mailReady=await syncMail(user);const results=await db().batch([db().prepare('SELECT * FROM lists WHERE owner=?').bind(user.userId),db().prepare('SELECT id,list_id,title,priority,deadline,done FROM tasks WHERE owner=?').bind(user.userId),db().prepare('SELECT id,title,content,filename,size FROM notes WHERE owner=? ORDER BY rowid DESC').bind(user.userId)]);return Response.json({user,lists:results[0].results,tasks:results[1].results,notes:results[2].results,mailReady},{headers:{'Cache-Control':'no-store'}})}catch(e){return fail(e)}}
export async function POST(request:Request){try{const user=await identity(request);if(Number(request.headers.get('content-length'))>20000)throw new HttpError('This request is too large.',413);const p=await request.json() as Record<string,any>;const owner=user.userId;const statements:D1PreparedStatement[]=[];
if(p.action==='saveList'){const name=title(p.title),rank=priority(p.priority),due=deadline(p.deadline);if(!['General','Year','Month','Week','Day'].includes(p.period))throw new HttpError('Choose a valid list type.');if(p.id){await owned('lists',p.id,owner);statements.push(db().prepare('UPDATE lists SET title=?,period=?,priority=?,deadline=? WHERE id=? AND owner=?').bind(name,p.period,rank,due,p.id,owner))}else statements.push(db().prepare('INSERT INTO lists(id,owner,title,period,priority,deadline) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),owner,name,p.period,rank,due))}
else if(p.action==='saveTask'){const name=title(p.title),rank=priority(p.priority),due=deadline(p.deadline);const list=await owned('lists',p.listId,owner);if(p.id){const task=await owned('tasks',p.id,owner);if(task.list_id!==list.id)throw new HttpError('Task does not belong to this list.');statements.push(db().prepare('UPDATE tasks SET title=?,priority=?,deadline=? WHERE id=? AND owner=?').bind(name,rank,due,p.id,owner))}else{statements.push(db().prepare('INSERT INTO tasks(id,owner,list_id,title,priority,deadline) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),owner,list.id,name,rank,due));statements.push(db().prepare('UPDATE lists SET done=0 WHERE id=? AND owner=?').bind(list.id,owner))}}
else if(p.action==='toggleTask'){if(typeof p.done!=='boolean')throw new HttpError('Choose a completion state.');const task=await owned('tasks',p.id,owner);statements.push(db().prepare('UPDATE tasks SET done=? WHERE id=? AND owner=?').bind(Number(p.done),p.id,owner));statements.push(db().prepare('UPDATE lists SET done=CASE WHEN EXISTS(SELECT 1 FROM tasks WHERE list_id=? AND done=0) THEN 0 ELSE 1 END WHERE id=? AND owner=?').bind(task.list_id,task.list_id,owner))}
else if(p.action==='setListDone'){if(typeof p.done!=='boolean')throw new HttpError('Choose a completion state.');await owned('lists',p.id,owner);statements.push(db().prepare('UPDATE lists SET done=? WHERE id=? AND owner=?').bind(Number(p.done),p.id,owner));statements.push(db().prepare('UPDATE tasks SET done=? WHERE list_id=? AND owner=?').bind(Number(p.done),p.id,owner))}
else throw new HttpError('Unknown action.');statements.push(dirty(owner));await db().batch(statements);const mailReady=await syncMail(user);return Response.json({ok:true,mailReady})}catch(e){return fail(e)}}

